version: "3.1"

services:

  mongo:
    image: mongo
    restart: always
    networks:
      - base
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: persons

  project:
    image: persons
    restart: always
    networks:
      - base
    build:
      context: .
    ports:
      - 8080:8080
    depends_on:
      - mongo
    links:
      - mongo

networks:
  base:
    driver: bridge